config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts, only: [:new, :create, :show, :edit, :update, :destroy]
  # resources :posts, except: [:index]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title,   presence: true
  validates :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:nickname])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all 
    @posts = Post.includes(:user)
  end

  def new
    @post_new  = Post.new
  end

  def create
    # binding.pry
    Post.create(post_params)
    redirect_to root_path
  end

  def show
    @post_show = Post.find(params[:id])
  end

  def edit
    @post_edit = Post.find(params[:id])
  end

  def update
    post_update = Post.find(params[:id])
    post_update.update(post_params)
    redirect_to post_path(post_update.id)
  end

  def destroy
    post_destroy = Post.find(params[:id])
    post_destroy.destroy()
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TecOurBlog200905</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class='header'>
      <div class='header__title'>
        <%= link_to "Our Blog", root_path, class:"header__title--text", method: :get %>
      </div>
      <div class="header__right">
        <% if user_signed_in? %>
          <%= link_to current_user.nickname, user_path(current_user.id), class: "header__right--btn" %>
          <%= link_to "新規投稿", new_post_path, class:"header__right--btn", method: :get %>
          <%= link_to "ログアウト", destroy_user_session_path, class:"header__right--btn", method: :delete %>
        <% else %>
          
          <%= link_to "ログイン", new_user_session_path, class:"header__right--btn", method: :get %>
          <%= link_to "新規登録", new_user_registration_path, class:"header__right--btn", method: :get %>
        <% end %>
      </div>
    </header>
    <div class='contents'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_tenpu.html.erb
  <div class="content">
    <div class="content__left">
      <div class="content__left--image">
      </div>
    </div>
    <div class="content__right">
      <div class="content__right__top">
        <%# <%= post.title%> 
        <%= link_to post.title, post_path(post.id), class:'content__right__top--title', method: :get %>
      </div>
      <div class="content__right__bottom">
        <div class="content__right__bottom--userName">
          <%= link_to post.user.nickname, user_path(post.user.id), class: "content__right__bottom--userName--btn" %>
        </div>
        <div class="content__right__bottom--date">
          <%= post.created_at%>
        </div>
      </div>
    </div>
  </div>

app/views/posts/edit.html.erb
<div class='content__title'>
  投稿の編集
</div>

<%= form_with model: @post_edit, class: :form, local: true do |form| %>
  <%= form.text_field :title, placeholder: :タイトル, class: :form__title %>
  <%= form.text_area :content, placeholder: :ブログ本文, class: :form__text %>
  <%= form.submit '編集する', class: :form__btn %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post_index| %>
  <%= render partial: "tenpu", locals: {post: post_index} %>
<% end %>

app/views/posts/new.html.erb
<div class = "content__title">
  新規記事の作成
</div>

<%= form_with model: @post_new, class: :form, local: true do |form| %>
  <%= form.text_field :title, placeholder: :タイトル, class: :form__title %>
  <%= form.text_area :content, placeholder: :ブログ本文, class: :form__text %>
  <%= form.submit '投稿する', class: :form__btn %>
<% end %>

app/views/posts/show.html.erb
<div class='postTitle'>
  <%= @post_show.title %>
</div>
<div class='postDate'>
  <%= @post_show.created_at %>
</div>
<div class='postAuthor'>
</div>
<%# <% if user_signed_in? && current_user.id == @post_show.user_id %> 
<% if user_signed_in? && current_user.id == @post_show.user_id%>
  <div class='postManage'>
    <%= link_to '編集', edit_post_path(@post_show.id), class: "postManage__edit", method: :get %>
    <%= link_to '削除', post_path(@post_show.id), class: "postManage__delete", method: :delete %>
  </div>
<% end %>
<div class= 'postText'>
  <%= simple_format @post_show.content %>
</div>

app/views/users/show.html.erb
<div class="postTitle">
  <%= @user.nickname %>さんの投稿一覧
</div>
<% @posts.each do |post_user_show| %>
  <%= render partial: "posts/tenpu", locals: {post: post_user_show} %>

  <%# <div class="content">
    <div class="content__left">
      <div class="content__left--image"></div>
    </div>
    <div class="content__right">
      <div class="content__right__top"> %>
        <%# <%= link_to post.title, post_path(post.id), class: "content__right__top--title" %> 
      <%# </div>
      <div class="content__right__bottom">
        <div class="content__right__bottom--userName"> %>
          <%# <%= link_to post.user.nickname, user_path(post.user), class: "content__right__bottom--userName--btn" %> 
        <%# </div>
        <div class="content__right__bottom--date">
          <%# <%= post.created_at %> 
        <%# </div>
      </div>
    </div>
  </div>   %>
<% end %>